### ISSUE TITLE
Widget closes when clicked

### ISSUE THREAD

**Issue by skaremanga** [orangebikelabs/opensqueeze#160]
When using the Widget (Large) it closes straight away and goes to the home screen again.

Running on an Odroid N2L Lineage OS Android 13 with Open Squeeze 2.7.0-alpha.51

Using 2.6.2 it works ok

**Comment by bensandee** [comment]
Thanks for the report, I'll check this out.

**Comment by skaremanga** [comment]
Great, let me know if I can do anything to help in the form of logfiles or testing

**Comment by bensandee** [comment]
You can try https://github.com/orangebikelabs/opensqueeze/releases/tag/v2.7.0-alpha.56 that fixes the crashy bug.

**Comment by skaremanga** [comment]
Tested and now it works as expected, thank you 😁
