### ISSUE TITLE
volume control doesn't work anymore

### ISSUE THREAD

**Issue by dizzy71** [orangebikelabs/opensqueeze#63]
Hi there,
Controlling the voulme doesn't work anymore in Android 13 (s22 ultra), neither within the app nor with the volume buttons. I could swear it worked a few days ago. Maybe the lastest sucurity update from Android?
Cheers,
Torsten

**Comment by dizzy71** [comment]
I'm sorry, updateing the LMS helped!!!

**Comment by bensandee** [comment]
thanks for handling the full lifecycle of this problem. glad it was resolved!
